export const ADD_TO_EXPENSE_LIST = 'ADD_TO_EXPENSE_LIST';
export const EDIT_EXPENSE_LIST = 'EDIT_EXPENSE_LIST';
export const REMOVE_FROM_EXPENSE_LIST = 'REMOVE_FROM_EXPENSE_LIST';
export const EMPTY_EXPENSE_LIST = 'EMPTY_EXPENSE_LIST';
export const ADD_TO_CURRENT_ROUTE = 'ADD_TO_CURRENT_ROUTE';